In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from keras import Sequential
from keras.layers import Dense

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,11,7]], columns = ['cgpa','profile_score', 'lpa'])

In [3]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,11,7


In [4]:
model = Sequential()
model.add(Dense(2,activation= 'linear', input_dim = 2))
model.add(Dense(1, activation = 'linear'))

c:\Users\Ali\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [6]:
model.get_weights()

[array([[ 0.8197018 , -0.41310304],
        [-1.0341824 , -0.0554179 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.27485847],
        [0.45273936]], dtype=float32),
 array([0.], dtype=float32)]

In [7]:
new_weights = [
    np.array([[0.1, 0.1], [0.1, 0.1]], dtype=np.float32),  # shape (input_dim, units) = (2,2)
    np.array([0., 0.], dtype=np.float32),                    # bias for first Dense layer
    np.array([[0.1], [0.1]], dtype=np.float32),              # shape (units, output_units) = (2,1)
    np.array([0.], dtype=np.float32)                         # bias for second Dense layer
]

In [8]:
model.set_weights(new_weights)

In [9]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [10]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [11]:
X = df.iloc[:,0:-1].values
y = df.iloc[:,-1].values
model.fit(X, y, epochs=100, verbose=1, batch_size=1)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 8s 140ms/step - loss: 27.9484
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 103ms/step - loss: 27.6299
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 97ms/step - loss: 27.3243 
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 106ms/step - loss: 26.9749
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 117ms/step - loss: 26.6406
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 150ms/step - loss: 26.2829
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - loss: 25.8986 
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 126ms/step - loss: 25.5413
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 144ms/step - loss: 25.1594
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 137ms/step - loss: 24.7445
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 166ms/step - loss: 24.3420
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 171ms/step - loss: 23.9352
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 111ms/step - loss: 23.4766
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 156ms/step - loss: 23.0393
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 103ms/step - los

In [ ]:
new_sample = np.array([[8.5, 8.5]], dtype=np.float32)  
pred = model.predict(new_sample)
print("Prediction for new sample:", pred[0,0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 934ms/step
Prediction for new sample: 5.6910934


In [13]:
for inp, true_val, pred_val in zip(X, y, predictions):
    print(f"Input={inp}, True={true_val}, Pred={pred_val[0]:.4f}")

NameError: name 'predictions' is not defined

In [ ]:
from sklearn.metrics import r2_score

predictions = model.predict(X)
print("MSE loss:", np.mean((y - predictions.flatten()) ** 2))
print("R2 score:", r2_score(y, predictions.flatten()))

for inp, true_val, pred_val in zip(X, y, predictions):
    print(f"Input={inp}, True={true_val}, Pred={pred_val[0]:.4f}")
