In [20]:
import numpy as np
import pandas as pd
import tensorflow as tf
from keras import Sequential
from keras.layers import Dense

In [21]:
df = pd.DataFrame([[8,8,1],[7,9,0],[6,10,1],[5,11,0]], columns = ['cgpa','profile_score', 'lpa'])

In [22]:
df.head()

,cgpa,profile_score,lpa
0,8,8,1
1,7,9,0
2,6,10,1
3,5,11,0


In [33]:
model = Sequential()
model.add(Dense(2,activation= 'sigmoid', input_dim = 2))
model.add(Dense(1, activation = 'sigmoid'))

c:\Users\Ali\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [24]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.get_weights()

[array([[ 0.39991736,  0.45161605],
        [-0.76302326,  1.1456367 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.18516791],
        [-1.3726045 ]], dtype=float32),
 array([0.], dtype=float32)]

In [26]:
new_weights = [
    np.array([[0.1, 0.1], [0.1, 0.1]], dtype=np.float32),  # shape (input_dim, units) = (2,2)
    np.array([0., 0.], dtype=np.float32),                    # bias for first Dense layer
    np.array([[0.1], [0.1]], dtype=np.float32),              # shape (units, output_units) = (2,1)
    np.array([0.], dtype=np.float32)                         # bias for second Dense layer
]

In [27]:
model.set_weights(new_weights)

In [28]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [29]:
optimizer = tf.keras.optimizers.Adam(learning_rate= 0.001)
model.compile(loss = 'binary_crossentropy',optimizer = optimizer)

In [30]:
model.fit(df[['cgpa','profile_score']], df['lpa'], epochs = 100 , verbose = 1, batch_size =1)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 5s 40ms/step - loss: 0.6977
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.6968 
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.6965 
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.6964 
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.6964 
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.6967 
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.6963 
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 108ms/step - loss: 0.6963
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 96ms/step - loss: 0.6963
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 71ms/step - loss: 0.6962
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 94ms/step - loss: 0.6961 
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 116ms/step - loss: 0.6960
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 148ms/step - loss: 0.6960
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 122ms/step - loss: 0.6961
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 104ms/step - loss: 0.6960
Epoch 1